name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0 # Update if needed

      - name: Restore dependencies
        run: dotnet restore
        working-directory: CalicotEncheres/Auctions

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: CalicotEncheres/Auctions

      - name: Publish
        run: dotnet publish -c Release -o published
        working-directory: CalicotEncheres/Auctions

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-calicot-dev-${{ secrets.AZURE_CODE_ID }}
          package: CalicotEncheres/Auctions/published
