name: Deploy Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Import SQL Database
        run: |
          az sql db import \
            --resource-group rg-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --server sqlsrv-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --name sqldb-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --admin-user ${{ secrets.TF_VAR_sql_admin_user}} \
            --admin-password ${{ secrets.TF_VAR_sql_admin_password }} \
            --storage-key-type SharedAccessKey \
            --storage-uri https://stcalicotprod000.blob.core.windows.net/db/Auctions_Data.bacpac
