name: Deploy Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Import SQL Database
        run: |
          az sql db import \
            --resource-group rg-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --server sqlsrv-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --name sqldb-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            --admin-user ${{ secrets.AZURE_SQL_ADMIN }} \
            --admin-password ${{ secrets.AZURE_SQL_PASSWORD }} \
            --storage-key-type SharedAccessKey \
            --storage-uri https://stcalicotprod000.blob.core.windows.net/db/Auctions_Data.bacpac
