name: Deploy Database

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQLPackage
        run: |
          wget https://aka.ms/sqlpackage-linux -O sqlpackage.zip
          unzip sqlpackage.zip -d sqlpackage
          chmod +x sqlpackage/sqlpackage
          sudo mv sqlpackage/sqlpackage /usr/local/bin/sqlpackage

      - name: Deploy BACPAC to Azure SQL
        run: |
          sqlpackage /a:Import \
            /sf:db/Auctions_Data.bacpac \
            /tsn:tcp:sqlsrv-calicot-dev-${{ secrets.AZURE_CODE_ID }}.database.windows.net \
            /tdn:sqldb-calicot-dev-${{ secrets.AZURE_CODE_ID }} \
            /tu:${{ secrets.TF_VAR_sql_admin_user }} \
            /tp:${{ secrets.TF_VAR_sql_admin_password }}
